export enum RabbitMQ {

  PartidosPoliticosQueue = 'partidos_politicos',
  CandidatosPoliticosQueue = 'candidatos_politicos',
  CentrosVotacionQueue = 'centro_votacion',
  JuntaReceptoraVotosQueue = 'junta_receptora_votos',
}

export enum JuntaReceptoraVotosMSG {
  CREATE = 'CREATE_JUNTA_RECEPTORA_VOTOS',
  UPDATE = 'UPDATE_JUNTA_RECEPTORA_VOTOS',
  DELETE = 'DELETE_JUNTA_RECEPTORA_VOTOS',
  FIND_ALL = 'FIND_JUNTAS_RECEPTORA_VOTOS',
  FIND_ONE = 'FIND_JUNTA_RECEPTORA_VOTOS',
  GET_MEMBERS_BY_JRV = 'GET_MEMBERS_BY_JRV',
  GET_MEMBER_BY_ID = 'GET_MEMBER_BY_ID',  
  CREATE_MEMBER = 'CREATE_MEMBER',  
}

export enum CandidatosPoliticosMSG {
  CREATE = 'CREATE_CANDIDATO_POLITICO',
  UPDATE = 'UPDATE_CANDIDATO_POLITICO',
  DELETE = 'DELETE_CANDIDATO_POLITICO',
  FIND_ALL = 'FIND_CANDIDATOS_POLITICOS',
  FIND_ONE = 'FIND__CANDIDATO_POLITICO',
  CHANGE_PHOTO = 'CHANGE_PHOTO_CANDIDATO_POLITICO',
}

export enum CentrosVotacionMSG {
  CREATE = 'CREATE_CENTRO_VOTACION',
  UPDATE = 'UPDATE_CENTRO_VOTACION',
  DELETE = 'DELETE_CENTRO_VOTACION',
  FIND_ALL = 'FIND_CENTROS_VOTACION',
  FIND_ONE = 'FIND_CENTRO_VOTACION',
  SET_STATUS = 'SET_STATUS',
}

export enum JrvMiembrosMSG {
  CREATE = 'CREATE_JUNTA_RECEPTORA_VOTOS',
  UPDATE = 'UPDATE_JUNTA_RECEPTORA_VOTOS',
  DELETE = 'DELETE_JUNTA_RECEPTORA_VOTOS',
  FIND_ALL = 'FIND_JUNTAS_RECEPTORA_VOTOS',
  FIND_ONE = 'FIND_JUNTA_RECEPTORA_VOTOS',
}

