export enum RabbitMQ {
  JuntaReceptoraVotosQueue = 'junta_receptora_votos',
  JrvMiembrosQueue = 'jrv_miembros', 
}

export enum JuntaReceptoraVotosMSG {
  CREATE = 'CREATE_JUNTA_RECEPTORA_VOTOS',
  UPDATE = 'UPDATE_JUNTA_RECEPTORA_VOTOS',
  DELETE = 'DELETE_JUNTA_RECEPTORA_VOTOS',
  FIND_ALL = 'FIND_JUNTAS_RECEPTORA_VOTOS',
  FIND_ONE = 'FIND_JUNTA_RECEPTORA_VOTOS',
  GET_MEMBERS_BY_JRV = 'GET_MEMBERS_BY_JRV',
  GET_MEMBER_BY_ID = 'GET_MEMBER_BY_ID',  
  CREATE_MEMBER = 'CREATE_MEMBER',  
}

export enum JrvMiembrosMSG {
  CREATE = 'CREATE_JUNTA_RECEPTORA_VOTOS',
  UPDATE = 'UPDATE_JUNTA_RECEPTORA_VOTOS',
  DELETE = 'DELETE_JUNTA_RECEPTORA_VOTOS',
  FIND_ALL = 'FIND_JUNTAS_RECEPTORA_VOTOS',
  FIND_ONE = 'FIND_JUNTA_RECEPTORA_VOTOS',
}